### ISSUE TITLE
Support for Julia Programming Language?

### ISSUE THREAD

**Issue by R0b0ty** [nikvdp/nvim-lsp-config#1]
This is a request for support of the [Julia Programming Language](https://www.julialang.org/) via **LspInstall**, as it is currently omitted from the list (when pressing tab after the `:LspInstall` command).  Thank you for your consideration!  Have a great day.

**Comment by nikvdp** [comment]
Hi @R0b0ty, glad to hear from you! The `:LspInstall` command this config actually uses comes from this plugin: https://github.com/kabouzeid/nvim-lspinstall.

I'd recommend you raise the issue on that repo. If/when they add support for Julia it will work with this repo's vim config as well.
