### ISSUE TITLE
Trying to get gopls working

### ISSUE THREAD

**Issue by awilliamson-puppet** [nikvdp/nvim-lsp-config#5]
Just want to say first thanks for this awesome repo; currently making the switch from VSCode. Trying to get gopls working but the server doesn't seem to attach on starting up. Did you have to do anything special to get it working?

**Comment by nikvdp** [comment]
hey @awilliamson-puppet, glad to hear from you! I didn't have to do anything special aside from the usual `:LspInstall go`. If you do `:LspInfo` you get a screen with some extra info including the path to a log file (should be on the second line of the window), that might give you some extra insight into why it's not attaching on your system

**Comment by awilliamson-puppet** [comment]
Hey thanks for the reply - I eventually got it working with the help of the log. Thank you very much!!

**Comment by nikvdp** [comment]
Great, glad you got it sorted out! What was the issue?

**Comment by awilliamson-puppet** [comment]
I had an empty go.mod file in my sample directory to satisfy the root_dir
pattern requirements, but since it was empty gopls was throwing a bunch of
errors. I switched to a .git file to satisfy the requirements and that
seems to have worked for basic testing of the autocomplete settings. Thanks
again for all this work - it is excellent!

**Comment by nikvdp** [comment]
Awesome, glad you’re enjoying it :)
