### ISSUE TITLE
nvim-lspinstall deprecated

### ISSUE THREAD

**Issue by rjorgenson-ns** [nikvdp/nvim-lsp-config#6]
Tried setting this up and fell down an lsp/lua rabbit hole trying to figure out why I kept getting errors.

kabouzeid/nvim-lspinstall has been deprecated and no longer works, there is an alternative installer https://github.com/williamboman/nvim-lsp-installer that supports new versions of neovim. There are more details that go over my head here https://github.com/neovim/nvim-lspconfig/issues/1075#issuecomment-980801779

**Comment by nikvdp** [comment]
Hey @rjorgenson-ns, sorry to hear about that. 

I have some fixes for that (among other things) in the [https://github.com/nikvdp/nvim-lsp-config/tree/neovim0.6-updates](neovim0.6-updates), I'll go ahead and merge those in, I believe they will the LSP issues

**Comment by rjorgenson-ns** [comment]
@nikvdp awesome that all worked great =] Thanks!
