### ISSUE TITLE
AutoStart for sourcekit failed: matching root directory not detected 

### ISSUE THREAD

**Issue by mcstrassell09** [nikvdp/nvim-lsp-config#8]
Hi, I installed nvim nightly and followed this repository to set up nvm-lsp. Running `:LspInstall swift` appears to install sourcekit successfully. However I get this error when opening  a swift file with nvim. I am new to vim. Thanks.

**Comment by nikvdp** [comment]
Hi @mcstrassell09, this is almost certainly an issue with the Swift LSP itself and/or your project layout or with [nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer). I don't use swift myself so I can't be of much help there, but you might consider opening an issue over at williamboman/nvim-lsp-installer. If you find a solution let me know and would be glad to add it to this repo as well!
